### ISSUE TITLE
wpinstall

### ISSUE THREAD

**Issue by certifiedloud** [bagley/wptool#1]
It would be awesome to have an install option that downloaded the files and created a database in a single command.

**Comment by certifiedloud** [comment]
I would also use this script as an installed option rather than a ephemeral solution.

**Comment by bagley** [comment]
Yes, that is one of the options I have been exploring. It would just need to get files [done], make database [todo], and then populate the database [todo]. If you have any knowledge of how to have wordpress do that last one, that would be great.

**Comment by bagley** [comment]
As far as using this as a permanent solution, rather than loading it into the shell, it would have to be split up into separate programs for each command, and then share. That sounds hard. An easier way would be to just put it in .bashrc to load it from a local source each time it runs. Something like this in the .bashrc:

. /usr/local/bin/wptool > /dev/null 2>&1

That way it loads into the shell, is usable, and doesn't show any info that it loaded. The only other way would be to make dummy files for each command that call a main file and run it. I'll think about it. Let me know if you have any ideas.
